### ISSUE TITLE
[feature]: merge functionality from Executor

### ISSUE THREAD

**Issue by JasonEleventeen** [hedgieinsocks/launcher#1]
Executor allows viewing results from a script, this extension allows executing, I'd like both :)

see https://extensions.gnome.org/extension/2932/executor/

**Comment by JasonEleventeen** [comment]
![image](https://user-images.githubusercontent.com/19441652/236086078-43442cf5-c89b-4263-a6a8-8648423093b1.png)

**Comment by hedgieinsocks** [comment]
@JasonEleventeen Hello, did I get it correctly that you are not quite content with the default logging and notify options of Launcher and would like to permanently display the result of the triggered scripts in a separate panel indicator (or even create separate indicators for each script)?

**Comment by JasonEleventeen** [comment]
I think executor actually reruns the script every N seconds and displays the result, that way I can have a script that check the VPN status and displays the result in the panel

**Comment by hedgieinsocks** [comment]
I see, it looks like you want to have both one-time-launch and loop-launch functionality in one extension instead of having to use two separate extensions to toggle VPN and to explicitly display its status (although the quick settings indicator should show VPN status as well and you should be able to toggle it off in quick settings). 

Anyway, this is far from the scope and simple purpose of this extension. Moreover, I do think that you'd be much better off with something more specific for your exact needs e.g. https://extensions.gnome.org/extension/4061/custom-vpn-toggler/ 

Perhaps there is some extension that implements the idea of custom-vpn-toggler in a custom and scalable way so the user can create dynamic indicator toggles for whatever services they wish. Or maybe someone (or even me) will write it in the future.
