### ISSUE TITLE
[feature]: running scripts with sudo

### ISSUE THREAD

**Issue by Erik-Bjerke** [hedgieinsocks/launcher#3]
It would be nice to be able to launch scripts as root, or to open the terminal when the script prompts for password because it contains "sudo", right now it just fails the execution.

**Comment by hedgieinsocks** [comment]
Yes, it would. But if the extension launches the script natively with sudo, one will get the error `sudo: a terminal is required to read the password`. So you can either try to use `sudo -S` commands in your script or add `user ALL=(ALL) NOPASSWD:ALL` or something less permissive to your sudoers configuration. Yes, these are terrible solutions security-wise but I don't see any other way.

**Comment by infeeeee** [comment]
I use `pkexec` instead of `sudo` for this: it shows a nice gui dialog asking for the password: 

- https://www.freedesktop.org/software/polkit/docs/0.105/pkexec.1.html
- https://wiki.archlinux.org/title/Polkit

e.g. I have a a script to restart a service, this is the full content of the file, works perfectly:

```shell
#!/bin/bash
pkexec systemctl restart logid.service
```

**Comment by Erik-Bjerke** [comment]
Thanks for your responses!
