### ISSUE TITLE
[feature]: custom icons for scripts

### ISSUE THREAD

**Issue by infeeeee** [hedgieinsocks/launcher#4]
Hello, and thank you for this extension! I love the simplicity!

It would be nice to set a custom icon and maybe a custom name to scripts.

Maybe as someway set in the files, with some special comment.

Or by naming them specifically e.g. `My nice script_iconname.sh`.

Thank you!

**Comment by hedgieinsocks** [comment]
Hi, thank you for your feedback and your suggestion!

**Comment by hedgieinsocks** [comment]
The extension does not track the scripts and I do not want to complicate things by creating a mapping for custom icons.
But I will add an option to disable generating icons from shebang. If you disable this option, the default arrow icon will be used instead. Alas, no icon variant won't do cause it will leave empty space on the left and make everything look skewed.
And then, you can rename your wrapper scripts with emoji to emulate custom icons.
![image](https://github.com/hedgieinsocks/launcher/assets/26518927/d755f440-fe27-4fb1-a7a0-b9c937dad64b)

**Comment by infeeeee** [comment]
Emoji is a good idea! 

What about parsing the filename, for freedesktop icon names? E.g. in your example the first file would be named `http_network-workgroup-symbolic` or something. 

Freedesktop icon specification is quite rigid, only alpahanumeric characters and dashes. Like you use the string for the settings icon: https://github.com/hedgieinsocks/launcher/blob/055885a55436f7c98de78f82231e5b77ac7cb009/extension.js#L138

But the emoji with arrow is good enough.

**Comment by hedgieinsocks** [comment]
Hmm, interesting. Honestly, I don't know how to easily get the list of icon names without spawning shell `find` command. But anyway, the first match might not always be right. So, I'd stick to emoji if one needs some candy for the eyes. As for the arrow, I find it the most fitting here. Though, I'd put a small bullet circle instead if it were available (I did not find such).

**Comment by hedgieinsocks** [comment]
Alternatively, one could specify the icon name inside the script as a comment e.g. after shebang so we can parse the script and set the icon if found. But it is a dirty hack and overkill imho :P

**Comment by infeeeee** [comment]
If you add a non existing icon name, what happens? If nothing really bad, I think the users can be trusted to find the icon name they want, and you don't have to check if the icon is correct or not. 

A lot other similar programs used to work this way, e.g. [argos](https://github.com/p-e-w/argos#display) and [command-menu](https://github.com/p-e-w/argos#display) (as far as I know, none of these work with current gnome version).

If you want to go with the emoji route, maybe other nice icon instead of the arrow would be `pan-end-symbolic`.

**Comment by hedgieinsocks** [comment]
I guess I did not get you quite right before. It looks like you suggested that the users should name their scripts with freedesktop icon names to get the corresponding icons. If so, we get a proper custom icon but an ugly and misleading script name.  As for a missing icon, it is just substituted for a crossed circle icon.

I could keep freedesktop icon names in an array and get the first matched icon name from the script name. But that would be far from ideal since one keyword is often featured in multiple icons. 

So I guess I'll end up with this so the user can choose the default `bullet` icon if need be:

![image](https://github.com/hedgieinsocks/launcher/assets/26518927/9c48c6cf-f65d-44c5-85c8-e40e5e1723cb)
